apiVersion: apps/v1
kind: Deployment
metadata:
  name: headroom
  namespace: caldera-system
  labels:
    app.kubernetes.io/name: headroom
    app.kubernetes.io/part-of: preview-headroom
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: headroom
  template:
    metadata:
      labels:
        app.kubernetes.io/name: headroom
        app.kubernetes.io/part-of: preview-headroom
    spec:
      priorityClassName: preview-headroom
      terminationGracePeriodSeconds: 0
      automountServiceAccountToken: false
      nodeSelector:
        karpenter.sh/nodepool: preview-environments
      securityContext:
        runAsNonRoot: true
        runAsUser: 65535
        runAsGroup: 65535
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: pause
          image: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.10
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 450m
              memory: 1Gi
            limits:
              cpu: 450m
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
