environment:
  name: ci
services:
  tremor:
    image:
      repository: tremor-api
      tag: main
  steward:
    image:
      repository: steward-api
      tag: main
postgres:
  image:
    repository: postgres
    tag: "17"
