service:
  name: ""
  port: 8000

image:
  repository: ""
  digest: ""

database:
  schema: ""
  secretName: ""

environment:
  name: ""
  vent: ""

replicas: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi
