{{- $environment := include "services.environmentName" . }}
{{- $labels := include "services.labels" . | fromYaml }}
{{- $databaseEnv := include "services.databaseEnv" . | fromYamlArray }}
{{- range $name, $overrides := .Values.services }}
{{- $service := mustMergeOverwrite (deepCopy $.Values.serviceDefaults) $overrides }}
---
{{ include "service.manifests" (dict
  "name" $name
  "namespace" $.Release.Namespace
  "labels" $labels
  "image" (merge (dict "registry" $.Values.image.registry) $service.image)
  "pullPolicy" $.Values.image.pullPolicy
  "port" $service.port
  "resources" $service.resources
  "priorityClassName" $.Values.priorityClassName
  "env" $databaseEnv
  "route" (dict
    "enabled" true
    "hostname" (printf "%s-%s.%s" $name $environment $.Values.domain)
    "labels" $.Values.routeLabels
    "gateway" $.Values.gateway)) }}
{{- end }}
